version: '3.8'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=signal
      - DB_PORT=5432
      - GIN_MODE=release
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      # Use the production stage, not the builder
      target: production
    ports:
      - "80:80"  # Uncommented to match Nginx config
    depends_on:
      - server
    networks:
      - app-network
    restart: unless-stopped
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=signal
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    restart: unless-stopped
networks:
  app-network:
    driver: bridge
volumes:
  postgres_data:
